SciTools/cube_browser

- lib/cube_browser/__init__.py
This is bare bones, no checks.  
When it makes the axes, it turns the cube's coordinate system into a GeoAxes but does not check whether the cube has a coord system in the first place, but this shouldn't be a problem if it is a temporary measure.
> Contourf skeleton

- lib/cube_browser/__init__.py
We should follow http://semver.org/
> Initial version.

- .travis.yml
- setup.py
Tidy of `setup.py` and added test runner
> Test runner

- .travis.yml
- lib/cube_browser/__init__.py
Again, no checks and no frills.
> Browser first attempt

- doc/Homepage.ipynb
- lib/cube_browser/__init__.py
defaults for setting up notebooks
> nb option defaults

- doc/Homepage.ipynb
- lib/cube_browser/__init__.py
- lib/cube_browser/tests/unit/test_Contour.py
- lib/cube_browser/tests/unit/test_Contourf.py
- lib/cube_browser/tests/unit/test_Pcolormesh.py
- lib/cube_browser/tests/unit/test_Pyplot.py
must be configured and passed in for all pyplot types
> axes mandated

- lib/cube_browser/__init__.py
- lib/cube_browser/tests/unit/test_Contour.py
- lib/cube_browser/tests/unit/test_Contourf.py
- lib/cube_browser/tests/unit/test_Pcolormesh.py
- lib/cube_browser/tests/unit/test_Pyplot.py
Early bird, and still to do ...
> Plot-type coords default and checking.

- .travis.yml
- doc/browsingCubes/browse.ipynb
- doc/browsingCubes/explore.ipynb
- lib/cube_browser/__init__.py
- lib/cube_browser/explorer.py
- lib/cube_browser/tests/unit/test_Browser.py
values for sliders
including time vals, which are now too long, need width
ipywidgets 5 (with work around)
> Slider vals

- setup.py
This PR provides complete `cube_browser` package discovery.
This will result in the tests being correctly packaged within the conda environment.
Closes #76.
> Fuller package discovery.

- doc/index.rst
@marqh @bjlittle @dkillick
This is a first attempt at adding some text to the introduction on the homepage.  Please let me know if you can see some areas of improvement or some better wording, or whatever.
> First text added to main intro page

- lib/cube_browser/explorer.py
> watch cubes

- doc/help.rst
- doc/index.rst
Please let me know if there are more links that I should add.
> help page added

- lib/cube_browser/explorer.py
with a try except due to Iris ValueError raising if sample_data_path not configured
> sample data path optional

- lib/cube_browser/__init__.py
- lib/cube_browser/tests/unit/test_Browser.py
> Fix slider description label wrapping.

- lib/cube_browser/explorer.py
> PEP8 of explorer.

- doc/explorers/intro.rst
- doc/index.rst
I have added a gist to the explore notebook as a link on the explorer page, as well as a download button.  
@marqh  @bjlittle 
I am not particularly happy about the gist.  I would rather be using mybinder.  As soon as we discuss and agree on this I can start implementing it (or whicherver alternative we choose).
> Static link added to index and small corrections made

- lib/cube_browser/__init__.py
- lib/cube_browser/explorer.py
future
file picker bug fix
plot title
ping @bjlittle
> explorer tweaks

- lib/cube_browser/explorer.py
> bugfix for not-Geoaxes

- README.md
> Add doc link to readme

- lib/cube_browser/__init__.py
- lib/cube_browser/explorer.py
explorer usability improvements from early user feedback
> Remove tab
